// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { AppendMessageApiV1SessionsConversationIdMessagesPostData, AppendMessageApiV1SessionsConversationIdMessagesPostErrors, AppendMessageApiV1SessionsConversationIdMessagesPostResponses, ChatApiV1ChatChatPostData, ChatApiV1ChatChatPostErrors, ChatApiV1ChatChatPostResponses, ChatStreamApiV1ChatChatStreamPostData, ChatStreamApiV1ChatChatStreamPostErrors, ChatStreamApiV1ChatChatStreamPostResponses, CreateConversationApiV1SessionsPostData, CreateConversationApiV1SessionsPostErrors, CreateConversationApiV1SessionsPostResponses, DeleteConversationApiV1SessionsConversationIdDeleteData, DeleteConversationApiV1SessionsConversationIdDeleteErrors, DeleteConversationApiV1SessionsConversationIdDeleteResponses, GetConversationApiV1SessionsConversationIdGetData, GetConversationApiV1SessionsConversationIdGetErrors, GetConversationApiV1SessionsConversationIdGetResponses, GetInfoApiV1KnowledgeInfoGetData, GetInfoApiV1KnowledgeInfoGetResponses, HealthCheckHealthGetData, HealthCheckHealthGetResponses, ListConversationsApiV1SessionsGetData, ListConversationsApiV1SessionsGetResponses, ListKnowledgeDocumentsApiV1KnowledgeListGetData, ListKnowledgeDocumentsApiV1KnowledgeListGetResponses, UpdateConversationApiV1SessionsConversationIdPatchData, UpdateConversationApiV1SessionsConversationIdPatchErrors, UpdateConversationApiV1SessionsConversationIdPatchResponses, UploadKnowledgeDocumentApiV1KnowledgeUploadPostData, UploadKnowledgeDocumentApiV1KnowledgeUploadPostErrors, UploadKnowledgeDocumentApiV1KnowledgeUploadPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * 对话接口（非流式）
 *
 * 非流式对话接口
 *
 * 发送消息并等待完整回复。
 */
export const chatApiV1ChatChatPost = <ThrowOnError extends boolean = false>(options: Options<ChatApiV1ChatChatPostData, ThrowOnError>): RequestResult<ChatApiV1ChatChatPostResponses, ChatApiV1ChatChatPostErrors, ThrowOnError> => (options.client ?? client).post<ChatApiV1ChatChatPostResponses, ChatApiV1ChatChatPostErrors, ThrowOnError>({
    url: '/api/v1/chat/chat',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 对话接口（SSE 流式）
 *
 * SSE 流式对话接口
 *
 * 事件类型：
 * - ``message``：回答内容片段
 * - ``sources``：引用来源（JSON 数组字符串）
 * - ``done``：回答完成（data 为 ``{conversation_id, skill_used}``）
 * - ``blocked``：被边界拦截器拦截（data 为拦截文案）
 * - ``error``：发生错误（data 为错误描述）
 */
export const chatStreamApiV1ChatChatStreamPost = <ThrowOnError extends boolean = false>(options: Options<ChatStreamApiV1ChatChatStreamPostData, ThrowOnError>): RequestResult<ChatStreamApiV1ChatChatStreamPostResponses, ChatStreamApiV1ChatChatStreamPostErrors, ThrowOnError> => (options.client ?? client).post<ChatStreamApiV1ChatChatStreamPostResponses, ChatStreamApiV1ChatChatStreamPostErrors, ThrowOnError>({
    url: '/api/v1/chat/chat/stream',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 获取知识库信息
 *
 * 获取当前知识库的基本信息
 */
export const getInfoApiV1KnowledgeInfoGet = <ThrowOnError extends boolean = false>(options?: Options<GetInfoApiV1KnowledgeInfoGetData, ThrowOnError>): RequestResult<GetInfoApiV1KnowledgeInfoGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetInfoApiV1KnowledgeInfoGetResponses, unknown, ThrowOnError>({ url: '/api/v1/knowledge/info', ...options });

/**
 * 上传知识文档
 *
 * 上传文档到知识库
 *
 * 支持 TXT、MD、PDF、CSV、JSON 格式，上传后将自动分块、向量化并存入 ChromaDB。
 */
export const uploadKnowledgeDocumentApiV1KnowledgeUploadPost = <ThrowOnError extends boolean = false>(options: Options<UploadKnowledgeDocumentApiV1KnowledgeUploadPostData, ThrowOnError>): RequestResult<UploadKnowledgeDocumentApiV1KnowledgeUploadPostResponses, UploadKnowledgeDocumentApiV1KnowledgeUploadPostErrors, ThrowOnError> => (options.client ?? client).post<UploadKnowledgeDocumentApiV1KnowledgeUploadPostResponses, UploadKnowledgeDocumentApiV1KnowledgeUploadPostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/v1/knowledge/upload',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * 列出知识库文档
 *
 * 列出知识库中的所有文档
 */
export const listKnowledgeDocumentsApiV1KnowledgeListGet = <ThrowOnError extends boolean = false>(options?: Options<ListKnowledgeDocumentsApiV1KnowledgeListGetData, ThrowOnError>): RequestResult<ListKnowledgeDocumentsApiV1KnowledgeListGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListKnowledgeDocumentsApiV1KnowledgeListGetResponses, unknown, ThrowOnError>({ url: '/api/v1/knowledge/list', ...options });

/**
 * 获取所有会话列表
 */
export const listConversationsApiV1SessionsGet = <ThrowOnError extends boolean = false>(options?: Options<ListConversationsApiV1SessionsGetData, ThrowOnError>): RequestResult<ListConversationsApiV1SessionsGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListConversationsApiV1SessionsGetResponses, unknown, ThrowOnError>({ url: '/api/v1/sessions', ...options });

/**
 * 创建新会话
 *
 * 创建或幂等获取会话。
 *
 * - 同一 ``conversation_id`` 重复 POST 会返回已有记录（避免重复建行）
 * - 标题为空时使用 ``"新对话"``
 */
export const createConversationApiV1SessionsPost = <ThrowOnError extends boolean = false>(options: Options<CreateConversationApiV1SessionsPostData, ThrowOnError>): RequestResult<CreateConversationApiV1SessionsPostResponses, CreateConversationApiV1SessionsPostErrors, ThrowOnError> => (options.client ?? client).post<CreateConversationApiV1SessionsPostResponses, CreateConversationApiV1SessionsPostErrors, ThrowOnError>({
    url: '/api/v1/sessions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 向会话追加一条消息（内部接口）
 *
 * chat 流式端点专用：把 user / assistant 消息写入 DB
 */
export const appendMessageApiV1SessionsConversationIdMessagesPost = <ThrowOnError extends boolean = false>(options: Options<AppendMessageApiV1SessionsConversationIdMessagesPostData, ThrowOnError>): RequestResult<AppendMessageApiV1SessionsConversationIdMessagesPostResponses, AppendMessageApiV1SessionsConversationIdMessagesPostErrors, ThrowOnError> => (options.client ?? client).post<AppendMessageApiV1SessionsConversationIdMessagesPostResponses, AppendMessageApiV1SessionsConversationIdMessagesPostErrors, ThrowOnError>({
    url: '/api/v1/sessions/{conversation_id}/messages',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 删除指定会话
 */
export const deleteConversationApiV1SessionsConversationIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteConversationApiV1SessionsConversationIdDeleteData, ThrowOnError>): RequestResult<DeleteConversationApiV1SessionsConversationIdDeleteResponses, DeleteConversationApiV1SessionsConversationIdDeleteErrors, ThrowOnError> => (options.client ?? client).delete<DeleteConversationApiV1SessionsConversationIdDeleteResponses, DeleteConversationApiV1SessionsConversationIdDeleteErrors, ThrowOnError>({ url: '/api/v1/sessions/{conversation_id}', ...options });

/**
 * 获取指定会话详情
 */
export const getConversationApiV1SessionsConversationIdGet = <ThrowOnError extends boolean = false>(options: Options<GetConversationApiV1SessionsConversationIdGetData, ThrowOnError>): RequestResult<GetConversationApiV1SessionsConversationIdGetResponses, GetConversationApiV1SessionsConversationIdGetErrors, ThrowOnError> => (options.client ?? client).get<GetConversationApiV1SessionsConversationIdGetResponses, GetConversationApiV1SessionsConversationIdGetErrors, ThrowOnError>({ url: '/api/v1/sessions/{conversation_id}', ...options });

/**
 * 更新会话（仅标题）
 */
export const updateConversationApiV1SessionsConversationIdPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateConversationApiV1SessionsConversationIdPatchData, ThrowOnError>): RequestResult<UpdateConversationApiV1SessionsConversationIdPatchResponses, UpdateConversationApiV1SessionsConversationIdPatchErrors, ThrowOnError> => (options.client ?? client).patch<UpdateConversationApiV1SessionsConversationIdPatchResponses, UpdateConversationApiV1SessionsConversationIdPatchErrors, ThrowOnError>({
    url: '/api/v1/sessions/{conversation_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Health Check
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthGetData, ThrowOnError>): RequestResult<HealthCheckHealthGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });
