// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

/**
 * Body_upload_knowledge_document_api_v1_knowledge_upload_post
 */
export type BodyUploadKnowledgeDocumentApiV1KnowledgeUploadPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * ChatMessage
 *
 * 单条对话消息
 */
export type ChatMessage = {
    role: MessageRole;
    /**
     * Content
     */
    content: string;
    /**
     * Timestamp
     */
    timestamp?: string;
    /**
     * Sources
     *
     * 引用的参考文献/数据来源
     */
    sources?: Array<string> | null;
    /**
     * Skill Used
     *
     * 使用的技能名称（pest_expert / fertilizer_calc / market_analyzer）
     */
    skill_used?: string | null;
};

/**
 * ChatRequest
 *
 * 用户对话请求
 */
export type ChatRequest = {
    /**
     * Message
     *
     * 用户输入的消息内容
     */
    message: string;
    /**
     * Conversation Id
     *
     * 对话会话ID，为空则创建新会话
     */
    conversation_id?: string | null;
};

/**
 * ChatResponse
 *
 * 对话响应（非流式）
 */
export type ChatResponse = {
    /**
     * Conversation Id
     *
     * 对话会话ID
     */
    conversation_id: string;
    /**
     * 助手回复消息
     */
    message: ChatMessage;
    /**
     * Blocked
     *
     * 是否被边界拦截器拦截
     */
    blocked?: boolean;
};

/**
 * ConversationCreate
 *
 * 创建会话请求体
 *
 * - ``title`` 可选，默认值在 service 层补齐
 * - ``conversation_id`` 可选；为空时由服务端生成
 */
export type ConversationCreate = {
    /**
     * Title
     *
     * 会话标题（为空时使用默认 "新对话"）
     */
    title?: string | null;
    /**
     * Conversation Id
     *
     * 客户端预生成的会话 ID（为空时由服务端生成）
     */
    conversation_id?: string | null;
};

/**
 * ConversationDetail
 *
 * 会话详情（含完整消息列表）
 */
export type ConversationDetail = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Messages
     */
    messages?: Array<MessageItem>;
    /**
     * Message Count
     *
     * 消息条数
     */
    message_count: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ConversationSummary
 *
 * 会话列表项（不含完整消息）
 */
export type ConversationSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Message Count
     *
     * 消息条数
     */
    message_count: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ConversationUpdate
 *
 * 更新会话（当前仅支持修改标题）
 */
export type ConversationUpdate = {
    /**
     * Title
     *
     * 新的会话标题
     */
    title?: string | null;
};

/**
 * DeleteResult
 *
 * 删除操作的统一响应
 */
export type DeleteResult = {
    /**
     * Message
     */
    message: string;
    /**
     * Id
     */
    id: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * KnowledgeBaseInfo
 *
 * 知识库信息
 */
export type KnowledgeBaseInfo = {
    /**
     * Name
     *
     * 知识库名称
     */
    name: string;
    /**
     * Document Count
     *
     * 文档数量
     */
    document_count: number;
    /**
     * Chunk Count
     *
     * 分块数量
     */
    chunk_count: number;
    /**
     * Last Updated
     *
     * 最后更新时间
     */
    last_updated?: string | null;
};

/**
 * KnowledgeUploadResponse
 *
 * 知识库文档上传响应
 */
export type KnowledgeUploadResponse = {
    /**
     * Success
     *
     * 是否上传成功
     */
    success: boolean;
    /**
     * Document Id
     *
     * 文档ID
     */
    document_id?: string | null;
    /**
     * Chunk Count
     *
     * 生成的分块数量
     */
    chunk_count?: number | null;
    /**
     * Message
     *
     * 响应消息
     */
    message: string;
};

/**
 * MessageAppend
 *
 * 向会话追加一条消息（内部接口，chat 流式端点调用）
 */
export type MessageAppend = {
    /**
     * Role
     */
    role: 'user' | 'assistant' | 'system';
    /**
     * Content
     */
    content: string;
    /**
     * Timestamp
     */
    timestamp?: string | null;
    /**
     * Sources
     */
    sources?: Array<string> | null;
    /**
     * Skill Used
     */
    skill_used?: string | null;
};

/**
 * MessageItem
 *
 * 会话中的一条消息（API 边界 DTO）
 *
 * 字段顺序与命名遵循 :class:`app.models.session.Conversation` 中
 * ``messages`` JSON 的存储格式，避免一次额外的字段重命名。
 */
export type MessageItem = {
    /**
     * Role
     *
     * 消息角色
     */
    role: 'user' | 'assistant' | 'system';
    /**
     * Content
     *
     * 消息文本内容
     */
    content: string;
    /**
     * Timestamp
     *
     * 消息时间戳（UTC）。未提供时由服务端填充。
     */
    timestamp?: string | null;
    /**
     * Sources
     *
     * 引用的参考文献/数据来源（仅 assistant 消息）
     */
    sources?: Array<string> | null;
    /**
     * Skill Used
     *
     * 使用的技能名称（pest_expert / fertilizer_calc / market_analyzer）
     */
    skill_used?: string | null;
};

/**
 * MessageRole
 *
 * 消息角色枚举
 */
export type MessageRole = 'user' | 'assistant' | 'system';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ChatApiV1ChatChatPostData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/chat/chat';
};

export type ChatApiV1ChatChatPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatApiV1ChatChatPostError = ChatApiV1ChatChatPostErrors[keyof ChatApiV1ChatChatPostErrors];

export type ChatApiV1ChatChatPostResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type ChatApiV1ChatChatPostResponse = ChatApiV1ChatChatPostResponses[keyof ChatApiV1ChatChatPostResponses];

export type ChatStreamApiV1ChatChatStreamPostData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/chat/chat/stream';
};

export type ChatStreamApiV1ChatChatStreamPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatStreamApiV1ChatChatStreamPostError = ChatStreamApiV1ChatChatStreamPostErrors[keyof ChatStreamApiV1ChatChatStreamPostErrors];

export type ChatStreamApiV1ChatChatStreamPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetInfoApiV1KnowledgeInfoGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/knowledge/info';
};

export type GetInfoApiV1KnowledgeInfoGetResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeBaseInfo;
};

export type GetInfoApiV1KnowledgeInfoGetResponse = GetInfoApiV1KnowledgeInfoGetResponses[keyof GetInfoApiV1KnowledgeInfoGetResponses];

export type UploadKnowledgeDocumentApiV1KnowledgeUploadPostData = {
    body: BodyUploadKnowledgeDocumentApiV1KnowledgeUploadPost;
    path?: never;
    query?: never;
    url: '/api/v1/knowledge/upload';
};

export type UploadKnowledgeDocumentApiV1KnowledgeUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadKnowledgeDocumentApiV1KnowledgeUploadPostError = UploadKnowledgeDocumentApiV1KnowledgeUploadPostErrors[keyof UploadKnowledgeDocumentApiV1KnowledgeUploadPostErrors];

export type UploadKnowledgeDocumentApiV1KnowledgeUploadPostResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeUploadResponse;
};

export type UploadKnowledgeDocumentApiV1KnowledgeUploadPostResponse = UploadKnowledgeDocumentApiV1KnowledgeUploadPostResponses[keyof UploadKnowledgeDocumentApiV1KnowledgeUploadPostResponses];

export type ListKnowledgeDocumentsApiV1KnowledgeListGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/knowledge/list';
};

export type ListKnowledgeDocumentsApiV1KnowledgeListGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListConversationsApiV1SessionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/sessions';
};

export type ListConversationsApiV1SessionsGetResponses = {
    /**
     * Response List Conversations Api V1 Sessions Get
     *
     * Successful Response
     */
    200: Array<ConversationSummary>;
};

export type ListConversationsApiV1SessionsGetResponse = ListConversationsApiV1SessionsGetResponses[keyof ListConversationsApiV1SessionsGetResponses];

export type CreateConversationApiV1SessionsPostData = {
    body: ConversationCreate;
    path?: never;
    query?: never;
    url: '/api/v1/sessions';
};

export type CreateConversationApiV1SessionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateConversationApiV1SessionsPostError = CreateConversationApiV1SessionsPostErrors[keyof CreateConversationApiV1SessionsPostErrors];

export type CreateConversationApiV1SessionsPostResponses = {
    /**
     * Successful Response
     */
    201: ConversationSummary;
};

export type CreateConversationApiV1SessionsPostResponse = CreateConversationApiV1SessionsPostResponses[keyof CreateConversationApiV1SessionsPostResponses];

export type AppendMessageApiV1SessionsConversationIdMessagesPostData = {
    body: MessageAppend;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/sessions/{conversation_id}/messages';
};

export type AppendMessageApiV1SessionsConversationIdMessagesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AppendMessageApiV1SessionsConversationIdMessagesPostError = AppendMessageApiV1SessionsConversationIdMessagesPostErrors[keyof AppendMessageApiV1SessionsConversationIdMessagesPostErrors];

export type AppendMessageApiV1SessionsConversationIdMessagesPostResponses = {
    /**
     * Successful Response
     */
    200: ConversationDetail;
};

export type AppendMessageApiV1SessionsConversationIdMessagesPostResponse = AppendMessageApiV1SessionsConversationIdMessagesPostResponses[keyof AppendMessageApiV1SessionsConversationIdMessagesPostResponses];

export type DeleteConversationApiV1SessionsConversationIdDeleteData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/sessions/{conversation_id}';
};

export type DeleteConversationApiV1SessionsConversationIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteConversationApiV1SessionsConversationIdDeleteError = DeleteConversationApiV1SessionsConversationIdDeleteErrors[keyof DeleteConversationApiV1SessionsConversationIdDeleteErrors];

export type DeleteConversationApiV1SessionsConversationIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: DeleteResult;
};

export type DeleteConversationApiV1SessionsConversationIdDeleteResponse = DeleteConversationApiV1SessionsConversationIdDeleteResponses[keyof DeleteConversationApiV1SessionsConversationIdDeleteResponses];

export type GetConversationApiV1SessionsConversationIdGetData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/sessions/{conversation_id}';
};

export type GetConversationApiV1SessionsConversationIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConversationApiV1SessionsConversationIdGetError = GetConversationApiV1SessionsConversationIdGetErrors[keyof GetConversationApiV1SessionsConversationIdGetErrors];

export type GetConversationApiV1SessionsConversationIdGetResponses = {
    /**
     * Successful Response
     */
    200: ConversationDetail;
};

export type GetConversationApiV1SessionsConversationIdGetResponse = GetConversationApiV1SessionsConversationIdGetResponses[keyof GetConversationApiV1SessionsConversationIdGetResponses];

export type UpdateConversationApiV1SessionsConversationIdPatchData = {
    body: ConversationUpdate;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/sessions/{conversation_id}';
};

export type UpdateConversationApiV1SessionsConversationIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateConversationApiV1SessionsConversationIdPatchError = UpdateConversationApiV1SessionsConversationIdPatchErrors[keyof UpdateConversationApiV1SessionsConversationIdPatchErrors];

export type UpdateConversationApiV1SessionsConversationIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ConversationDetail;
};

export type UpdateConversationApiV1SessionsConversationIdPatchResponse = UpdateConversationApiV1SessionsConversationIdPatchResponses[keyof UpdateConversationApiV1SessionsConversationIdPatchResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
